# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "jupyterlab" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      top-level-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "jupyterlab/packages/jupyterlab-jupytext-extension" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      jupytext-extension-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "jupyterlab/packages/jupyterlab-jupytext-extension/ui-tests" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      jupytext-extension-ui-tests-dependencies:
        patterns:
          - "*"
