# This environment is smaller than the dev environment.
# In particular it does not include JupyterLab nor the community notebook extensions
name: jupytext-ci
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter
  - ipykernel
  - nbconvert
  - nbformat<=5.0.8
  - pyyaml
  - toml
  - markdown-it-py~=0.6.0
  - pip
  - pytest
  - pytest-cov
  - coverage
  - flake8
  - autopep8
  - black
  - isort>=5.3.0
  - pandoc>=2.11
  - sphinx-gallery<0.8
  - pre-commit
  - gitpython
