name: jupytext-dev
channels:
  - default
  - conda-forge
dependencies:
  - python==3.7
  - jupyter
  - jupyterlab
  - pyyaml
  - nbconvert
  - jupyter_contrib_nbextensions
  - pytest
  - pytest-xdist
  - pylint
  - flake8
  - black
  - autopep8
  - sphinx-gallery
  - nodejs<13
  - yarn
  - pip
  - setuptools
  - pandoc
