name: jupytext-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - jupyterlab>=3.0
  - nbformat<=5.0.8
  - jupyter-packaging
  - pyyaml
  - toml
  - markdown-it-py~=0.6.0
  - nbconvert
  - ipykernel
  - jupyter_contrib_nbextensions
  - pytest
  - pytest-xdist
  - pytest-cov
  - pre-commit
  - gitpython
  - pylint
  - flake8
  - black
  - isort
  - autopep8
  - sphinx-gallery<0.8
  - pip
  - setuptools
  - twine
  - pandoc>=2.11
  # make html in docs folder
  - sphinx
  - tox-conda
  - pip:
    - sphinx_copybutton
