name: jupytext-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - jupyter
  - jupyterlab
  - pyyaml
  - toml
  - nbconvert
  - ipykernel
  - jupyter_contrib_nbextensions
  - pytest
  - pytest-xdist
  - pytest-cov
  - pre-commit
  - pylint
  - flake8
  - black
  - isort
  - autopep8
  - sphinx-gallery<0.8
  - nodejs
  - yarn
  - pip
  - setuptools
  - twine
  - pandoc>=2.9
  # make html in docs folder
  - sphinx
  - tox-conda
  - pip:
    - sphinx_copybutton
    - myst_parser
