# This environment is smaller than the dev environment.
# In particular it does not include JupyterLab, community notebook extensions,
# nor the libraries that are not available for Python 2.7
name: jupytext-ci
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter
  - ipykernel
  - nbconvert
  - pyyaml
  - toml
  - pip
  - pytest
  - pytest-cov
  - pre-commit
  - coverage
  - flake8
  - pandoc>=2.11
  # pathlib is required on Python 2
  - pathlib
