# This environment is smaller than the dev environment.
#
# Until conda supports creating env from pyproject.toml
# (https://github.com/conda/conda/pull/12666)
# we need to maintain environment-ci.yml file that is inline with deps in
# pyproject.toml
#
name: jupytext-ci
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - nbconvert
  - nbformat>=5.1.2
  - pyyaml
  - toml
  - markdown-it-py
  - mdit-py-plugins
  - pip
  - pytest
  - pytest-randomly
  - pytest-cov
  - coverage
  - flake8
  - autopep8
  - black
  - isort
  - pandoc>=3.0
  - sphinx-gallery<0.8
  - pre-commit
  - gitpython
